baseURL = "http://www.transition-espace-ephemere.com"
defaultContentLanguage = "fr"
disableLanguages = []
ignoreErrors = ["error-remote-getjson"]
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Transition | Musée Ephémère du Street Art"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Transition - Ephemeral Street Art Museum - All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Transition - Ephemeral Street Art Museum - All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "line-up"
name = "Line-Up"
weight = 1
[[menu.footer]]
URL = "news"
name = "News"
weight = 2
[[menu.footer]]
URL = "transition"
name = "Transition"
weight = 3
[[menu.footer]]
URL = "partners"
name = "Partenaires"
weight = 4
[[menu.footer]]
URL = "info"
name = "Info"
weight = 5
[[menu.footer]]
URL = "education-nationale"
name = "Eucation Nationale"
weight = 5
[[menu.main]]
URL = "line-up"
name = "Line-Up"
weight = 2
[[menu.main]]
URL = "news"
name = "News"
weight = 3
[[menu.main]]
URL = "transition"
hasChildren = true
name = "Transition"
weight = 4
[[menu.main]]
URL = "transition#project"
name = "Le projet"
parent = "Transition"
weight = 1
[[menu.main]]
URL = "transition#location"
name = "Le lieu"
parent = "Transition"
weight = 2
[[menu.main]]
URL = "transition#anru"
name = "Le projet ANRU"
parent = "Transition"
weight = 3
[[menu.main]]
URL = "partners"
name = "Partenaires"
weight = 5
[[menu.main]]
URL = "info"
name = "Info"
weight = 6
[[menu.main]]
URL = "education-nationale"
name = "Education Nationale"
weight = 7
[params]
author = "[Developed by Florian Dambrine](http://floriandambrine.com/) [& Alexis Latraye]"
description = "Ephemeral Street Art Museum "
email = "transition@gmail.com"
google_analitycs_id = ""
location = "Quartier du soleil levant - 80100 Abbeville"
logo = "images/logo_sm.png"
mobile = "0124857985320"
[params.covid]
message = "**Attention ⚠️** !\nSuite aux nouvelles mesures gouvernementales, et malgré la jauge diminuée, nous sommes dans l’obligation de demander __le pass sanitaire aux plus de 18 ans (test pcr ou antigenique de moins de 3 jours, vaccination ou certificat de rétablissement Covid)__.\nSi ce n’est pas possible pour vous, annulez vos réservations en utilisant le lien de la confirmation de réservation que vous avez reçu par mail. Nous ne faisons pas d’annulation par téléphone. Merci de votre compréhension.\n"
[params.eventbrite]
message = "Réservation pour une visite nocturne le samedi 28 août à partir de 20h00.  En raison du trop grand nombre de personnes souhaitant visiter , et pour vous éviter une trop longue attente sur le parking, nous avons pris la décision avec regret de passer par notre site de réservation.  Nous en sommes réellement désolé, mais la sécurité est primordiale.  Merci de votre compréhension.  Pass sanitaire à jour et masque obligatoire.  A demain . "
url = "https://www.billetweb.fr/transition-last-night"
url_edu = ""
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "50.109020"
map_longitude = "1.850730"
map_marker = "images/marker.png"
[params.instagram]
appid = "..."
token = "..."
[params.maintenance]
enable = false
image = "images/affiche-coming-soon-01.jpg"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ion-social-instagram-outline"
link = "https://www.instagram.com/transition_espace_ephemere/"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "https://www.facebook.com/transitionespaceephemere"
[privacy.instagram]
disable = false
