---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url:
sections:
- type: heading
  label: Site

- type: directory
  path: content/french/
  label: Home
  create: documents
  match: "_index.md"

- type: directory
  path: content/french/info
  label: Infos
  create: documents
  match: "_index.md"
  templates:
  - info

- type: directory
  path: content/french/line-up
  label: Line-Up
  create: documents
  match: "**/*"
  templates:
  - artist


- type: directory
  path: content/french/news
  label: News
  create: none
  match: "**/*"
  templates:
  - news

- type: directory
  path: content/french/partners
  label: Partners
  create: documents
  match: "**/*"
  templates:
  - partners

- type: directory
  path: content/french/transition
  create: documents
  match: "**/*"
  templates:
  - transition

- type: heading
  label: Configuration
- type: directory
  path: "."
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.67.0
  preview_output_directory: public
  preview_docker_image: peaceiris/hugo:v0.65.3-mod
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
